services:
  flipsite:
    build: .
    container_name: flipsite
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/avollrath/FlipSite-local/main/public/docker-icon.svg
      net.unraid.docker.webui: http://[IP]/flipsite/
    ports:
      - "5001:5000"
    volumes:
      - /mnt/cache/appdata/flipsite:/data
